"""add_retry_count_to_posts

Revision ID: 79007369c157
Revises: 750d0d1ef448
Create Date: 2026-05-28 19:32:33.114149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79007369c157'
down_revision: Union[str, Sequence[str], None] = '750d0d1ef448'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('retry_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'retry_count')
    # ### end Alembic commands ###
